### ISSUE TITLE
Not able to upgrade engine-munger(version 1.1.1)

### ISSUE THREAD

**Issue by mailto-kkk** [krakenjs/express-enrouten#76]
Hi,

I am using the node version of 5.3.0.
I am trying to upgrade the below module.

```
     I. engine-munger from the version 0.2.8 to 1.1.1
II. adarois from the version 0.1.10 to 1.0.1
III. dustjs-linkedin from the version 2.6.2 to 2.7.2
```

when I give the command "npm install", it is giving the below error message

Unhandled rejection Error: Cannot find module 'engine-munger/lib/expressView'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)

Can you please provide some suggestions?

@lmarkus

**Comment by mailto-kkk** [comment]
Posted in wrong module.. so I am closing the issue
